#'pullADAPSData
#'
#'function to load in ADAPS precipitation unit data for use in regressions
#'
#'@param siteNo string USGS ADAPS station id
#'@param stormLoad data frame generated by pullLoadData
#'@return df data frame containing ADAPS precip data for the selected site
#' loadFile <- "EastRiverVolumesLoads.csv"
#' pullLoadData(loadFile)
pullADAPSData <- function(siteNo,stormLoad) {
  StartDt <- strftime(min(stormLoad[which(stormLoad$frozen=='N'),]$Start,na.rm=TRUE) - (60*60*24*5),'%Y-%m-%d')
  EndDt <- strftime(max(stormLoad[which(stormLoad$frozen=='N'),]$End,na.rm=TRUE) + (60*60*24*5),'%Y-%m-%d')
  adaps_precip_in <- retrieveUnitNWISData(siteNo,'00045',StartDt,EndDt,format="tsv")
  colnames(adaps_precip_in) <- c("agency_cd","site_no","pdate","tz_cd","rain","remark")
  df <- adaps_precip_in[,c(5,3)]
  colnames(df) <- c("rain","pdate")
  return(df)
}